### ISSUE TITLE
Hello! Need some help!

### ISSUE THREAD

**Issue by oookotooo** [internap/fake-switches#77]
Maybe you have some guide how to run it on fresh ubuntu 14.04? For example: run cisco router, so it could be accessable via ssh on port 11001.

I tried this, and got errors:
```
root@perignon:/home/kkin/fake-switches-1.1.6_pypi# python tests/cisco/test_cisco_switch_protocol.py 
Traceback (most recent call last):
  File "tests/cisco/test_cisco_switch_protocol.py", line 20, in <module>
    from tests.util.global_reactor import cisco_privileged_password
ImportError: No module named tests.util.global_reactor
```

Also I run setup.py install, even don't recognize what it actually did =)

**Comment by mat128** [comment]
Hello and thanks for your interest in our project :)

I agree, there should be more guidance as to how to use our project. Currently, we do not expose any entry point, so it is more like a library than a utility. If you simply want to run a Cisco  device "out of the box", you can use part of what is indicated in the readme:

```
from twisted.internet import reactor
from fake_switches.switch_configuration import SwitchConfiguration, Port
from fake_switches.ssh_service import SwitchSshService
from fake_switches.cisco.cisco_core import CiscoSwitchCore

ssh_service = SwitchSshService(
    ip="127.0.0.1",
    ssh_port=11001,
    switch_core=CiscoSwitchCore(SwitchConfiguration("127.0.0.1", "my_switch", ports=[Port("FastEthernet0/1"), Port("FastEthernet0/2"), Port("FastEthernet0/3")])))
ssh_service.hook_to_reactor(reactor)
print('Starting reactor')
reactor.run()
```
Executing this file should print to the screen "Starting reactor". Once you see this, you can
ssh root@127.0.0.1 -p 11001

The default password should be "root". Then the enable password is "", simply press enter.

```
$ ssh root@127.0.0.1 -p 11001
The authenticity of host '[127.0.0.1]:11001 ([127.0.0.1]:11001)' can't be established.
RSA key fingerprint is db:cc:5a:0e:8b:33:4c:f5:8b:b9:43:24:70:00:71:4b.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '[127.0.0.1]:11001' (RSA) to the list of known hosts.
root@127.0.0.1's password:
my_switch>enable
Password:
my_switch#show run
Building configuration...

Current configuration : 136 bytes
version 12.1
!
hostname my_switch
!
!
vlan 1
!
interface FastEthernet0/1
!
interface FastEthernet0/2
!
interface FastEthernet0/3
!
end

my_switch#
```

What were you expecting on the user experience side with this project? We thought of creating classes of devices (for example, a Cisco WS-C2960S-48TS-L would have 48 GigabitEthernet ports pre-configured, etc., etc.). What do you think?

Lastly, we'd be very interested in knowing what is your use case, if you don't mind :)

**Comment by oookotooo** [comment]
Did run that code:
```
from twisted.internet import reactor
from fake_switches.switch_configuration import SwitchConfiguration, Port
from fake_switches.ssh_service import SwitchSshService
from fake_switches.cisco.cisco_core import CiscoSwitchCore

ssh_service = SwitchSshService(
    ip="127.0.0.1",
    ssh_port=11001,
    switch_core=CiscoSwitchCore(SwitchConfiguration("127.0.0.1", "my_switch", ports=[Port("FastEthernet0/1"), Port("FastEthernet0/2"), Port("FastEthernet0/3")])))
ssh_service.hook_to_reactor(reactor)
print('Starting reactor')
reactor.run()
```
and got this import error:

```
root@perignon:/home/kkin/fake-switches# python fakeswgit.py 
Traceback (most recent call last):
  File "fakeswgit.py", line 3, in <module>
    from fake_switches.ssh_service import SwitchSshService
  File "/home/kkin/fake-switches/fake_switches/ssh_service.py", line 18, in <module>
    from twisted.conch import avatar, interfaces as conchinterfaces
ImportError: No module named conch
```
It is interesting thing for me to use it instead of UNL or GNS3, because they use too much RAM and CPU. I wish to use ansible modules for cisco routers for fast configuration of a small park of devices, created by fake switches =)

Thanks!

**Comment by oookotooo** [comment]
I think it would be great to create switch via this library and wrap it in docker container for example. So you can spawn any amount of routers =)

**Comment by mat128** [comment]
That's a really good idea :) Feel free to send a PR, even if it's just tentative stuff, we'd be happy to look at it :)

**Comment by mbelang** [comment]
I think you need to do this:

Have you install fake switch locally?
`python setup.py install`

You can test it locall first by doing it in a virtualenv generated by tox
```
root@perignon:/home/kkin/fake-switches# tox -r
root@perignon:/home/kkin/fake-switches# . .tox/bin/activate
root@perignon:/home/kkin/fake-switches# python fakeswgit.py
```

or create a local virtualenv
```
root@perignon:/home/kkin/fake-switches# virtualenv fake-switch-venv
root@perignon:/home/kkin/fake-switches# . fake-switch-venv/bin/activate
root@perignon:/home/kkin/fake-switches# python setup.py install
root@perignon:/home/kkin/fake-switches# python fakeswgit.py
```

**Comment by mat128** [comment]
We could also add a "venv" to tox so we could run it like ``tox -evenv -- python fakeswgit.py``

**Comment by oookotooo** [comment]
Hi again!
I created an docker container with python:2.7.12(debian jessie) and did this:
```
root@perignon:/home/kkin# docker run -v /tmp/app/:/tmp/app/ -it python:2.7.12 /bin/bash
root@736e2a6ea3fb:/tmp/app/fake-switches# python setup.py install
root@736e2a6ea3fb:/tmp/app/fake-switches# pip install tox
root@736e2a6ea3fb:/tmp/app/fake-switches# pip install netaddr
root@736e2a6ea3fb:/tmp/app/fake-switches# pip install tftpy
root@736e2a6ea3fb:/tmp/app/fake-switches# pip install pycrypto
root@736e2a6ea3fb:/tmp/app/fake-switches# pip install Twisted
root@736e2a6ea3fb:/tmp/app/fake-switches# pip install pyasn1
root@736e2a6ea3fb:/tmp/app/fake-switches# pip install nose
root@736e2a6ea3fb:/tmp/app/fake-switches# pip install mock
root@736e2a6ea3fb:/tmp/app/fake-switches# pip install pyhamcrest
root@736e2a6ea3fb:/tmp/app/fake-switches# pip install pexpect
root@736e2a6ea3fb:/tmp/app/fake-switches# pip install flexmock
root@736e2a6ea3fb:/tmp/app/fake-switches# pip install ncclient
root@736e2a6ea3fb:/tmp/app/fake-switches# apt-get update
root@736e2a6ea3fb:/tmp/app/fake-switches# apt-get install telnetd
root@736e2a6ea3fb:/tmp/app/fake-switches# apt-get install telnet
root@736e2a6ea3fb:/tmp/app/fake-switches# /etc/init.d/openbsd-inetd restart
root@736e2a6ea3fb:/tmp/app/fake-switches# tox -r
```
and what i got on docker with python 2.7.12:

```
======================================================================
ERROR: test_posting_delete_on_both_auto_negotiation_flags_delete_and_raises (tests.juniper_qfx_copper.juniper_qfx_copper_protocol_test.JuniperQfxCopperProtocolTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/app27/fake-switches/tests/juniper/__init__.py", line 10, in setUp
    self.nc = self.create_client()
  File "/tmp/app27/fake-switches/tests/juniper_qfx_copper/juniper_qfx_copper_protocol_test.py", line 40, in create_client
    device_params={'name': 'junos'}
  File "/tmp/app27/fake-switches/.tox/py27/lib/python2.7/site-packages/ncclient/manager.py", line 153, in connect
    return connect_ssh(*args, **kwds)
  File "/tmp/app27/fake-switches/.tox/py27/lib/python2.7/site-packages/ncclient/manager.py", line 118, in connect_ssh
    session.connect(*args, **kwds)
  File "/tmp/app27/fake-switches/.tox/py27/lib/python2.7/site-packages/ncclient/transport/ssh.py", line 379, in connect
    raise SSHError('Negotiation failed')
SSHError: Negotiation failed
-------------------- >> begin captured logging << --------------------
ncclient.transport.session: DEBUG: <SSHSession(session, initial daemon)> created: client_capabilities=<dictionary-keyiterator object at 0x7f7e840885d0>
ncclient.transport.ssh: DEBUG: starting thread (client mode): 0x7e124450L
ncclient.transport.ssh: DEBUG: Local version/idstring: SSH-2.0-paramiko_2.0.2
ncclient.transport.ssh: DEBUG: Remote version/idstring: SSH-2.0-Twisted
ncclient.transport.ssh: INFO: Connected (version 2.0, client Twisted)
ncclient.transport.ssh: DEBUG: kex algos:[u'diffie-hellman-group1-sha1', u'diffie-hellman-group14-sha1'] server key:[u'ssh-rsa'] client encrypt:[u'aes256-ctr', u'aes256-cbc', u'aes192-ctr', u'aes192-cbc', u'aes128-ctr', u'aes128-cbc', u'cast128-ctr', u'cast128-cbc', u'blowfish-ctr', u'blowfish-cbc', u'3des-ctr', u'3des-cbc'] server encrypt:[u'aes256-ctr', u'aes256-cbc', u'aes192-ctr', u'aes192-cbc', u'aes128-ctr', u'aes128-cbc', u'cast128-ctr', u'cast128-cbc', u'blowfish-ctr', u'blowfish-cbc', u'3des-ctr', u'3des-cbc'] client mac:[u'hmac-sha2-512', u'hmac-sha2-256', u'hmac-sha1', u'hmac-md5'] server mac:[u'hmac-sha2-512', u'hmac-sha2-256', u'hmac-sha1', u'hmac-md5'] client compress:[u'none', u'zlib'] server compress:[u'none', u'zlib'] client lang:[u''] server lang:[u''] kex follows?False
ncclient.transport.ssh: DEBUG: Kex agreed: diffie-hellman-group1-sha1
ncclient.transport.ssh: DEBUG: Cipher agreed: aes128-ctr
ncclient.transport.ssh: DEBUG: MAC agreed: hmac-sha2-256
ncclient.transport.ssh: DEBUG: Compression agreed: none
ncclient.transport.ssh: ERROR: Exception: Signature verification (ssh-rsa) failed.
ncclient.transport.ssh: ERROR: Traceback (most recent call last):
ncclient.transport.ssh: ERROR:   File "/tmp/app27/fake-switches/.tox/py27/lib/python2.7/site-packages/paramiko/transport.py", line 1774, in run
ncclient.transport.ssh: ERROR:     self.kex_engine.parse_next(ptype, m)
ncclient.transport.ssh: ERROR:   File "/tmp/app27/fake-switches/.tox/py27/lib/python2.7/site-packages/paramiko/kex_group1.py", line 75, in parse_next
ncclient.transport.ssh: ERROR:     return self._parse_kexdh_reply(m)
ncclient.transport.ssh: ERROR:   File "/tmp/app27/fake-switches/.tox/py27/lib/python2.7/site-packages/paramiko/kex_group1.py", line 111, in _parse_kexdh_reply
ncclient.transport.ssh: ERROR:     self.transport._verify_key(host_key, sig)
ncclient.transport.ssh: ERROR:   File "/tmp/app27/fake-switches/.tox/py27/lib/python2.7/site-packages/paramiko/transport.py", line 1623, in _verify_key
ncclient.transport.ssh: ERROR:     raise SSHException('Signature verification (%s) failed.' % self.host_key_type)
ncclient.transport.ssh: ERROR: SSHException: Signature verification (ssh-rsa) failed.
ncclient.transport.ssh: ERROR: 
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 414 tests in 176.462s

FAILED (errors=1)
ERROR: InvocationError: '/tmp/app27/fake-switches/.tox/py27/bin/python setup.py nosetests'
____________________________________________________________________________________________________ summary ____________________________________________________________________________________________________
ERROR:   py27: commands failed
```

But also i got somehow it working on my desktop ubuntu 14.04!

**Comment by stephanerobert** [comment]
Yeah.. This is an intermittent problem we've been facing. We didn't have the time to give it the love it needs.
We will have to investigate further.

**Comment by oookotooo** [comment]
Finally got it working in ubuntu:14.04 container. I will write my results tomorrow and finish this issue =)

**Comment by stephanerobert** [comment]
Excellent! Thank you for contributing!

**Comment by oookotooo** [comment]
I almost got working [container](https://github.com/oookotooo/SoftServe-1/blob/master/fake-switches-dockerfiles/Dockerfile), but, i don't know now how to run these:
`CMD . .tox/py27/bin/activate && python start.py`
it execute it once and exit, so, it can be started now only inside image `docker run -it --rm fake-switches bash`

Also maybe installing openssl on debian will fix issue with ssh, but it is freezes on my pc for some reason.
Also if you use `pip install -q $PKG` against `pip install $PKG` it wont build!

**Comment by oookotooo** [comment]
I have some trouble:
```
root@perignon:/home/kkin/DockerizedFakeSwitches# docker run -it -p 11001:2222 fake-switches bash
root@f73854c643ce:/tmp/app/fake-switches# . .tox/py27/bin/activate
(py27) root@f73854c643ce:/tmp/app/fake-switches# python start.py 
```
and connection is refused, can it be fixed?
```
root@perignon:/home/kkin# ssh root@localhost -p 11001
ssh_exchange_identification: Connection closed by remote host
```

**Comment by oookotooo** [comment]
i have configured switch working on 5555 port but i have `ssh_exchange_identification: Connection closed by remote host`, i actually don't know how to fix it...

**Comment by oookotooo** [comment]
Finally got working container. Here is [Dockerfile](https://github.com/oookotooo/SoftServe-1/blob/master/fake-switches-dockerfiles/Dockerfile)
I think it is resolved for now =)

**Comment by oookotooo** [comment]
still have errors in automated buld in [docker](https://hub.docker.com/r/oookotooo/tmp/builds/bcztbnyznt2kndgsvu6dqkm/), but i have good news! it is working on debian!
