### ISSUE TITLE
Builds often fail because of SSHError: Negotiation failed

### ISSUE THREAD

**Issue by mat128** [internap/fake-switches#92]
Seems to be a paramiko / connectivity issue... happens way to often for us to ignore.

```
======================================================================
ERROR: test_bad_configuration_element (tests.juniper.juniper_base_protocol_test.JuniperBaseProtocolTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/internap/fake-switches/tests/juniper/__init__.py", line 10, in setUp
    self.nc = self.create_client()
  File "/home/travis/build/internap/fake-switches/tests/juniper/juniper_base_protocol_test.py", line 38, in create_client
    device_params={'name': 'junos'}
  File "/home/travis/build/internap/fake-switches/.tox/py27/lib/python2.7/site-packages/ncclient/manager.py", line 154, in connect
    return connect_ssh(*args, **kwds)
  File "/home/travis/build/internap/fake-switches/.tox/py27/lib/python2.7/site-packages/ncclient/manager.py", line 119, in connect_ssh
    session.connect(*args, **kwds)
  File "/home/travis/build/internap/fake-switches/.tox/py27/lib/python2.7/site-packages/ncclient/transport/ssh.py", line 393, in connect
    raise SSHError('Negotiation failed')
SSHError: Negotiation failed
-------------------- >> begin captured logging << --------------------
ncclient.transport.session: DEBUG: <SSHSession(session, initial daemon)> created: client_capabilities=<dictionary-keyiterator object at 0x7f9fcdaeda48>
ncclient.transport.ssh: DEBUG: starting thread (client mode): 0xcca44210L
ncclient.transport.ssh: DEBUG: Local version/idstring: SSH-2.0-paramiko_2.1.1
ncclient.transport.ssh: DEBUG: Remote version/idstring: SSH-2.0-Twisted
ncclient.transport.ssh: INFO: Connected (version 2.0, client Twisted)
ncclient.transport.ssh: DEBUG: kex algos:[u'diffie-hellman-group1-sha1', u'diffie-hellman-group14-sha1'] server key:[u'ssh-rsa'] client encrypt:[u'aes256-ctr', u'aes256-cbc', u'aes192-ctr', u'aes192-cbc', u'aes128-ctr', u'aes128-cbc', u'cast128-ctr', u'cast128-cbc', u'blowfish-ctr', u'blowfish-cbc', u'3des-ctr', u'3des-cbc'] server encrypt:[u'aes256-ctr', u'aes256-cbc', u'aes192-ctr', u'aes192-cbc', u'aes128-ctr', u'aes128-cbc', u'cast128-ctr', u'cast128-cbc', u'blowfish-ctr', u'blowfish-cbc', u'3des-ctr', u'3des-cbc'] client mac:[u'hmac-sha2-512', u'hmac-sha2-256', u'hmac-sha1', u'hmac-md5'] server mac:[u'hmac-sha2-512', u'hmac-sha2-256', u'hmac-sha1', u'hmac-md5'] client compress:[u'none', u'zlib'] server compress:[u'none', u'zlib'] client lang:[u''] server lang:[u''] kex follows?False
ncclient.transport.ssh: DEBUG: Kex agreed: diffie-hellman-group1-sha1
ncclient.transport.ssh: DEBUG: Cipher agreed: aes128-ctr
ncclient.transport.ssh: DEBUG: MAC agreed: hmac-sha2-256
ncclient.transport.ssh: DEBUG: Compression agreed: none
ncclient.transport.ssh: ERROR: Exception: Signature verification (ssh-rsa) failed.
ncclient.transport.ssh: ERROR: Traceback (most recent call last):
ncclient.transport.ssh: ERROR:   File "/home/travis/build/internap/fake-switches/.tox/py27/lib/python2.7/site-packages/paramiko/transport.py", line 1778, in run
ncclient.transport.ssh: ERROR:     self.kex_engine.parse_next(ptype, m)
ncclient.transport.ssh: ERROR:   File "/home/travis/build/internap/fake-switches/.tox/py27/lib/python2.7/site-packages/paramiko/kex_group1.py", line 75, in parse_next
ncclient.transport.ssh: ERROR:     return self._parse_kexdh_reply(m)
ncclient.transport.ssh: ERROR:   File "/home/travis/build/internap/fake-switches/.tox/py27/lib/python2.7/site-packages/paramiko/kex_group1.py", line 111, in _parse_kexdh_reply
ncclient.transport.ssh: ERROR:     self.transport._verify_key(host_key, sig)
ncclient.transport.ssh: ERROR:   File "/home/travis/build/internap/fake-switches/.tox/py27/lib/python2.7/site-packages/paramiko/transport.py", line 1627, in _verify_key
ncclient.transport.ssh: ERROR:     raise SSHException('Signature verification (%s) failed.' % self.host_key_type)
ncclient.transport.ssh: ERROR: SSHException: Signature verification (ssh-rsa) failed.
ncclient.transport.ssh: ERROR: 
--------------------- >> end captured logging << ---------------------
```

**Comment by mat128** [comment]
Fixed in #93.
